# **Projeto: Previsão de Intenção de Compra de Clientes em Loja Web**

**Descrição do Projeto**

Neste projeto, nosso objetivo é criar um sistema inteligente para antecipar a intenção de compra dos clientes em um site de e-commerce. Imagine poder prever quais clientes têm maior probabilidade de realizar compras online, com base em suas características e comportamentos passados. Essa capacidade de prever a intenção de compra não só aprimorará a experiência do cliente, mas também permitirá que a empresa direcione seus esforços de marketing de forma mais eficaz.

**Objetivo**

Queremos desenvolver um modelo preditivo capaz de analisar os padrões de comportamento dos clientes e identificar sinais que indicam a propensão deles para realizar compras no site da empresa. Para isso, vamos usar uma base de dados que contém informações detalhadas sobre os clientes, incluindo:

Dados demográficos (idade, renda, etc.)

Informações sobre compras anteriores

# Base de dados:

Year_Birth: Ano de nascimento do cliente.

Education: Nível de escolaridade do cliente.

Marital_Status: Estado civil do cliente.

Income: Renda anual da família do cliente.

Kidhome: Número de crianças na casa do cliente.

Recency: Número de dias desde a última compra do cliente.

Complain: 1 se o cliente reclamou nos últimos 2 anos, 0 caso contrário.

MntWines: Valor gasto em vinhos nos últimos 2 anos.

MntFruits: Valor gasto em frutas nos últimos 2 anos.

MntMeatProducts: Valor gasto em carnes nos últimos 2 anos.

MntFishProducts: Valor gasto em peixes nos últimos 2 anos.

MntSweetProducts: Valor gasto em doces nos últimos 2 anos.

MntGoldProds: Valor gasto em produtos de ouro nos últimos 2 anos.

NumDealsPurchases: Número de compras feitas com desconto

NumStorePurchases: Número de compras feitas diretamente nas lojas.

NumWebVisitsMonth: Número de visitas ao site da empresa no último mês.






**WebPurchases: Número de compras feitas pelo site da empresa.**

# ETAPA 1:

**Preparação dos Dados**

**Exploração e Limpeza:** Analisar e limpar os dados para garantir que estejam prontos para a modelagem.

**Análise:** Construa uma storytelling com gráficos, analisando e retirando insights das informações.

In [56]:
# Biblioteca de dataframe
import pandas as pd
import numpy as np

# Biblioteca para visualização de dados e análise gráfica
import plotly_express as px

# Bibliotecas de preparação do modelo
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split

# Biblioteca do modelo
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

# Biblioteca de avaliação do modelo
from sklearn.metrics import classification_report, confusion_matrix

# Bibliotecas de codificação e padronização
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from scipy.stats import zscore
from scipy.stats import randint
from scipy.stats import loguniform
from sklearn.model_selection import RandomizedSearchCV

In [57]:
base = pd.read_csv('marketing_campaign.csv', delimiter=';')

In [58]:
# Visualização do dataframe
base.head()

,Year_Birth,Education,Marital_Status,Income,Kidhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumStorePurchases,NumWebVisitsMonth,Complain,WebPurchases
0,1957,Graduation,Single,58138.0,0,58,635,88,546,172,88,88,4,7,0,1
1,1954,Graduation,Single,46344.0,1,38,11,1,6,2,1,6,2,5,0,0
2,1965,Graduation,Together,71613.0,0,26,426,49,127,111,21,42,10,4,0,1
3,1984,Graduation,Together,26646.0,1,26,11,4,20,10,3,5,4,6,0,0
4,1981,PhD,Married,58293.0,1,94,173,43,118,46,27,15,6,5,0,1

In [59]:
# Análise de tipos de dados e possíveis dados faltantes
base.info()

<class 'pandas.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year_Birth         2240 non-null   int64
 1   Education          2240 non-null   str
 2   Marital_Status     2240 non-null   str
 3   Income             2216 non-null   float64
 4   Kidhome            2240 non-null   int64
 5   Recency            2240 non-null   int64
 6   MntWines           2240 non-null   int64
 7   MntFruits          2240 non-null   int64
 8   MntMeatProducts    2240 non-null   int64
 9   MntFishProducts    2240 non-null   int64
 10  MntSweetProducts   2240 non-null   int64
 11  MntGoldProds       2240 non-null   int64
 12  NumStorePurchases  2240 non-null   int64
 13  NumWebVisitsMonth  2240 non-null   int64
 14  Complain           2240 non-null   int64
 15  WebPurchases       2240 non-null   int64
dtypes: float64(1), int64(13), str(2)
memory usage: 280.1 KB

Há duas colunas de dados escritos, serão transformadas em códigos numéricos.

A coluna de salário tem 24 dados nulos ou faltantes.

In [60]:
# Usando describe para observar a presença de outliers
base.describe()

,Year_Birth,Income,Kidhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumStorePurchases,NumWebVisitsMonth,Complain,WebPurchases
count,2240.000000,2216.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000
mean,1968.805804,52247.251354,0.444196,49.109375,303.935714,26.302232,166.950000,37.525446,27.062946,44.021875,5.790179,5.316518,0.009375,0.503571
std,11.984069,25173.076661,0.538398,28.962453,336.597393,39.773434,225.715373,54.628979,41.280498,52.167439,3.250958,2.426645,0.096391,0.500099
min,1893.000000,1730.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1959.000000,35303.000000,0.000000,24.000000,23.750000,1.000000,16.000000,3.000000,1.000000,9.000000,3.000000,3.000000,0.000000,0.000000
50%,1970.000000,51381.500000,0.000000,49.000000,173.500000,8.000000,67.000000,12.000000,8.000000,24.000000,5.000000,6.000000,0.000000,1.000000
75%,1977.000000,68522.000000,1.000000,74.000000,504.250000,33.000000,232.000000,50.000000,33.000000,56.000000,8.000000,7.000000,0.000000,1.000000
max,1996.000000,666666.000000,2.000000,99.000000,1493.000000,199.000000,1725.000000,259.000000,263.000000,362.000000,13.000000,20.000000,1.000000,1.000000

In [61]:
'''
Como temos colunas de caracteres vamos transformá-los em numéricos primeiro
'''
encoder = LabelEncoder()
base['Education'] = encoder.fit_transform(base['Education'])
base['Marital_Status'] = encoder.fit_transform(base['Marital_Status'])

In [62]:
base.head()

,Year_Birth,Education,Marital_Status,Income,Kidhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumStorePurchases,NumWebVisitsMonth,Complain,WebPurchases
0,1957,2,4,58138.0,0,58,635,88,546,172,88,88,4,7,0,1
1,1954,2,4,46344.0,1,38,11,1,6,2,1,6,2,5,0,0
2,1965,2,5,71613.0,0,26,426,49,127,111,21,42,10,4,0,1
3,1984,2,5,26646.0,1,26,11,4,20,10,3,5,4,6,0,0
4,1981,4,3,58293.0,1,94,173,43,118,46,27,15,6,5,0,1

In [63]:
'''
Após observar a presença de possíveis outliers vamos usar z-score para limpar os dados
'''
base = base.astype(float)
# Achando o z-score para cada variável numérica do dataframe
z_score = base.apply(zscore)
mask = ~(z_score.abs() > 3).any(axis=1)
base_limpa = base[mask]

In [64]:
# Observando quantos dados foram eliminados e a possível presença de outliers
base_limpa.describe()

,Year_Birth,Education,Marital_Status,Income,Kidhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumStorePurchases,NumWebVisitsMonth,Complain,WebPurchases
count,1985.000000,1985.000000,1985.000000,1963.000000,1985.000000,1985.000000,1985.000000,1985.000000,1985.000000,1985.000000,1985.000000,1985.000000,1985.000000,1985.000000,1985.0,1985.000000
mean,1968.891184,2.427708,3.725441,49895.346409,0.488161,49.139547,275.442317,19.627708,132.385894,28.522418,20.537028,37.591940,5.605542,5.501259,0.0,0.474055
std,11.561383,1.126987,1.067142,24478.131195,0.545312,29.043907,320.634043,29.446455,180.426347,41.729576,30.777357,43.214694,3.180724,2.200422,0.0,0.499452
min,1940.000000,0.000000,1.000000,7500.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
25%,1960.000000,2.000000,3.000000,34176.000000,0.000000,24.000000,20.000000,1.000000,14.000000,2.000000,1.000000,8.000000,3.000000,4.000000,0.0,0.000000
50%,1970.000000,2.000000,4.000000,48726.000000,0.000000,49.000000,138.000000,7.000000,52.000000,10.000000,7.000000,21.000000,4.000000,6.000000,0.0,0.000000
75%,1977.000000,3.000000,5.000000,64921.000000,1.000000,74.000000,452.000000,24.000000,171.000000,36.000000,26.000000,48.000000,8.000000,7.000000,0.0,1.000000
max,1996.000000,4.000000,6.000000,666666.000000,2.000000,99.000000,1311.000000,143.000000,843.000000,201.000000,150.000000,200.000000,13.000000,10.000000,0.0,1.000000

In [65]:
'''
Tendo em vista que já foi feito a limpeza de outliers e codificação de caracteres é razoável eliminar os dados nulos da coluna 'Income', por causa de seu pequeno volume.
'''
base_limpa= base_limpa.dropna(subset=['Income'])
base_limpa = base_limpa[base_limpa['Income'] != 666666]

In [66]:
base_limpa.isna().sum()

Year_Birth           0
Education            0
Marital_Status       0
Income               0
Kidhome              0
Recency              0
MntWines             0
MntFruits            0
MntMeatProducts      0
MntFishProducts      0
MntSweetProducts     0
MntGoldProds         0
NumStorePurchases    0
NumWebVisitsMonth    0
Complain             0
WebPurchases         0
dtype: int64

In [67]:
# Verificando contagens de dados
base_limpa['WebPurchases'].value_counts()

WebPurchases
0.0    1030
1.0     932
Name: count, dtype: int64

In [68]:
# Verificando correlação de income com compras pelo site da empresa
fig = px.histogram(
    base_limpa,
    x='Income',
    color=base_limpa['WebPurchases'].map({0.0:'Não', 1.0:'Sim'}),
    color_discrete_map={'Sim':'#414f96', 'Não':'#1cfcc8'},
    template = 'seaborn',
    title = 'Salário x Compras pelo site',
    barmode= 'overlay',
)
fig.update_layout(
    xaxis=dict(
        title='Salário'
    ),
    yaxis=dict(
        title='Contagem'
    ),
    legend=dict(
        title='Compras pelo site'
    )
)
fig.show()

Observa-se uma correlação semelhante à uma distribuição normal quando relacionamos salário à compras pelo site, mas essa relação atinge seu pico por volta dos 70k.

In [69]:
# Vendo a contagem para a variável educação
base_limpa['Education'].value_counts()

Education
2.0    957
4.0    446
3.0    337
0.0    169
1.0     53
Name: count, dtype: int64

In [70]:
# Verificando correlação de Ano de nascimento com compras pelo site da empresa
fig = px.histogram(
    base_limpa,
    x='Year_Birth',
    color=base_limpa['WebPurchases'].map({0.0:'Não', 1.0:'Sim'}),
    color_discrete_map={'Sim':'#1bab42', 'Não':'#ab1b25'},
    template = 'seaborn',
    title = 'Ano de nascimento x Compras pelo site',
    barmode= 'group',
)
fig.update_layout(
    xaxis=dict(
        title='Ano de nascimento'
    ),
    yaxis=dict(
        title='Contagem'
    ),
    legend=dict(
        title='Compras pelo site'
    )
)
fig.show()

Parece haver uma correlação negativa entre o ano de nascimento e a realização de compras pelo site

In [71]:
# Relação entre nível educacional e compras pelo site da empresa
fig = px.histogram(
    base_limpa,
    x=base_limpa['Education'].map({0.0:'Graduação', 1.0:'Pós-Graduação', 2.0:'Mestrado', 3.0:'Doutorado', 4.0:'PhD'}),
    color=base_limpa['WebPurchases'].map({0.0:'Não', 1.0:'Sim'}),
    color_discrete_map={'Sim':'#1bab42', 'Não':'#ab1b25'},
    template = 'seaborn',
    title = 'Educação x Compras pelo site',
    barmode= 'group',
)
fig.update_layout(
    xaxis=dict(
        title='Nível Educacional'
    ),
    yaxis=dict(
        title='Contagem'
    ),
    legend=dict(
        title='Compras pelo site'
    )
)
fig.show()

A correlação entre o nível educacional e as compras pelo site da empresa não se mostrou efetiva.

In [72]:
# Relação entre compras de objetos feitos com ouro e compras realizadas pelo site da empresa
fig = px.histogram(
    base_limpa,
    x='MntGoldProds',
    color=base_limpa['WebPurchases'].map({0.0:'Não', 1.0:'Sim'}),
    color_discrete_map={'Sim':'#1bab42', 'Não':'#ab1b25'},
    template = 'seaborn',
    title = 'Produtos em ouro x Compras pelo site',
    barmode= 'group',
)
fig.update_layout(
    xaxis=dict(
        title=' Valor gasto em produtos em ouro'
    ),
    yaxis=dict(
        title='Contagem'
    ),
    legend=dict(
        title='Compras pelo site'
    )
)
fig.show()

Parece que para valores pequenos os consumidores preferem realizar compras preferencialmente, mas para valores altos a relação inverte.

# ETAPA 2:
**Pré-processamento**

**Análise Correlação:** Verifique a correlação entre as váriaveis e análise se há espaço para retirar váriaveis que não te parecem importantes.

**Codificação de Variáveis Categóricas:** Transformar variáveis categóricas em um formato que os modelos de machine learning possam interpretar.


**Separe a base em Y, X e Treino e teste:**: Faça a separação da base.

**Realize a padronização dos dados**: Padronize os dados para garantir eficiência no modelo e eficácia.

In [100]:
# Gráfico de correlação entre as variáveis
corr =  base_limpa.corr()
fig = px.imshow(
    corr,
    text_auto=True,
    aspect='full',
    color_continuous_scale='Tealgrn',
    template='seaborn',
    title='Matriz de correlação'
)
fig.show()

In [74]:
'''
Como a codificação de variáveis categóricas foi feita na etapa acima, não é necessário realizá-la de novo.
Nessa etapa, a coluna 'Complain' será eliminada porque os valores relativos à presença de reclamações foram eliminados por conter outliers em alguma outra variável.
Além disso, os valores serão padronizados e o PCA será utilizado para selecionar as variáveis que podem explicar melhor a variável target
'''

base_limpa = base_limpa.drop(columns='Complain')

# Separando em X e Y.
X = base_limpa.drop(columns='WebPurchases')
Y = base_limpa['WebPurchases']

In [75]:
# Padronizando valores das variáveis
pad_scaler = StandardScaler()
X_pad = pad_scaler.fit_transform(X)
X_pad = pd.DataFrame(X_pad, columns=X.columns, index=X.index)

In [76]:
X_pad.head()

,Year_Birth,Education,Marital_Status,Income,Kidhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumStorePurchases,NumWebVisitsMonth
0,-1.031084,-0.378978,0.261011,0.425100,-0.893289,0.309115,1.116530,2.332865,2.286384,3.438351,2.192577,1.166303,-0.506422,0.681268
1,-1.290630,-0.378978,0.261011,-0.160809,0.945780,-0.380150,-0.825658,-0.633995,-0.701333,-0.635753,-0.635247,-0.731998,-1.134886,-0.227707
2,-0.338962,-0.378978,1.197217,1.094518,-0.893289,-0.793709,0.466022,1.002893,-0.031863,1.976467,0.014827,0.101402,1.378968,-0.682195
3,1.304829,-0.378978,1.197217,-1.139377,0.945780,-0.793709,-0.825658,-0.531690,-0.623874,-0.444030,-0.570240,-0.755148,-0.506422,0.226781
4,1.045283,1.395615,-0.675194,0.432800,0.945780,1.549793,-0.321436,0.798282,-0.081658,0.418721,0.209850,-0.523648,0.122041,-0.227707

In [77]:
# Utilizando o PCA para observar as variáveis necessárias ao modelo
pca = PCA(n_components=10)
pca.fit(X_pad)

PCA(n_components=10)

In [78]:
# Gráfico de variância explicada acumulada
exp_cul = np.cumsum(pca.explained_variance_ratio_)

fig = px.area(
    x=range(1, exp_cul.shape[0]+1),
    y=exp_cul,
    labels={'x':'Número de componentes', 'y':'Variância explicada'},
    template = 'seaborn',
    title='Gráfico de PCA'
)
fig.update_traces(line_color='#2aa889')
fig.show()

Com 10 componentes/variáveis pode-se explicar 91% da variabilidade dos dados da base.

In [79]:
X_pca = pca.fit_transform(X_pad)

In [80]:
# Dividindo a base em treino e teste
X_train, X_test, Y_train, Y_test = train_test_split(X_pca, Y, test_size=0.3, random_state=42)

# ETAPA 3:

**Modelagem**

Escolha ao menos 2 técnicas de machine learning e rode 2 modelos, afim de identificar qual tem o melhor resultado para essa base. Lembrando que estamos lidando com uma classificação binária.

In [86]:
# Primeiro modelo treinado será o de regressão logística
lr_model = LogisticRegression(random_state=42)

# Procurando melhores hiperparâmetros para o modelo
log_par = {
    'C': loguniform(1e-3, 1e3),
    'penalty':[None, 'l2'],
    'solver': ['newton-cg', 'lbfgs']
}
rsearch_log = RandomizedSearchCV(
    estimator=lr_model,
    param_distributions=log_par,
    n_iter=100,
    n_jobs=-1,
    cv=5
)
rsearch_log.fit(X_train, Y_train)

D:\PyCharm 2025.3\Modelagem_1\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(

RandomizedSearchCV(cv=5, estimator=LogisticRegression(random_state=42),
                   n_iter=100, n_jobs=-1,
                   param_distributions={'C': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x00000251473C78A0>,
                                        'penalty': [None, 'l2'],
                                        'solver': ['newton-cg', 'lbfgs']})

In [88]:
# Pontuação de treino do modelo de regressão logística
melhor_logreg = rsearch_log.best_score_
print(f'Melhor pontuação do modelo: {melhor_logreg:.2f}')

Melhor pontuação do modelo: 0.84

In [91]:
# Treino de modelo de random forest
rf_model = RandomForestClassifier(random_state=42)

# Seleção de hiperparâmetros
rf_par = {
    'n_estimators':randint(50, 200),
    'criterion':['gini', 'entropy'],
    'max_depth':range(1,30),
    'min_samples_split':range(2,30),
    'max_features':['sqrt', 'log2'],
}

# Configurando o modelo com hiperparâmetros
rsearch_rf = RandomizedSearchCV(
    estimator=rf_model,
    param_distributions=rf_par,
    cv = 5,
    n_iter=100,
    n_jobs=-1,
)
rsearch_rf.fit(X_train, Y_train)

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42),
                   n_iter=100, n_jobs=-1,
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': range(1, 30),
                                        'max_features': ['sqrt', 'log2'],
                                        'min_samples_split': range(2, 30),
                                        'n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x00000251471225D0>})

In [92]:
# Melhor pontuação de treino do random forest
melhor_rf = rsearch_rf.best_score_
print(f"Melhor pontuação do modelo: {melhor_rf:.2f}")

Melhor pontuação do modelo: 0.88

A pontuação de treino do modelo de random forest foi ligeiramente melhor, mas a pontuação dos dois modelos foi satisfatória.

# ETAPA 4:

**Avaliação**

Avalie os resultados encontrados nos dois modelos e identifique qual te pareceu realizar melhor as previsões.

Utilize além das métricas padrões a matriz de confusão.

In [94]:
# Teste do modelo de regressão logística
Y_pred_lr = rsearch_log.predict(X_test)

# Gráfico da matriz de confusão
conf_log = confusion_matrix(Y_test, Y_pred_lr)

classes = ['Não compra web', 'Compra web']
fig = px.imshow(
    conf_log,
    text_auto=True,
    aspect='auto',
    template='seaborn',
    x=classes,
    y=classes,
    labels=dict(x='Predição', y='Real', color='Contagem'),
    color_continuous_scale='Temps',
    title='Matriz de confusão - Regressão logística'
)
fig.show()

A Matriz de confusão do modelo de regressão logística mostrou uma boa quantidade de acertos no teste.

In [95]:
# Relatório de classificação do modelo de regressão logística
print("Relatório de classificação")
print(classification_report(Y_test, Y_pred_lr))

Relatório de classificação
              precision    recall  f1-score   support

         0.0       0.82      0.89      0.85       314
         1.0       0.86      0.77      0.81       275

    accuracy                           0.83       589
   macro avg       0.84      0.83      0.83       589
weighted avg       0.84      0.83      0.83       589

O modelo demonstrou uma acurácia e uma média ponderada de 0.83, ou seja, a diferença entre treino e teste foi ínfima. Isso demonstra que o modelo foi bem preparado e treinado.

In [97]:
# Teste de modelo de random forest
Y_pred_rf = rsearch_rf.predict(X_test)

# Gráfico de matriz de confusão
conf_rf = confusion_matrix(Y_test, Y_pred_rf)

classes = ['Não compra web', 'Compra web']
fig = px.imshow(
    conf_rf,
    text_auto=True,
    aspect='auto',
    template='seaborn',
    x=classes,
    y=classes,
    labels=dict(x='Predição', y='Real', color='Contagem'),
    color_continuous_scale='Temps',
    title='Matriz de confusão - Random forest'
)
fig.show()

Assim como na etapa de treino, o modelo de random forest foi ligeiramente melhor que o de regressão logística na fase de teste.

In [98]:
# Relatório de classificação do modelo de random forest
print("Relatório de classificação")
print(classification_report(Y_test, Y_pred_rf))

Relatório de classificação
              precision    recall  f1-score   support

         0.0       0.93      0.89      0.91       314
         1.0       0.88      0.92      0.90       275

    accuracy                           0.90       589
   macro avg       0.90      0.90      0.90       589
weighted avg       0.90      0.90      0.90       589

O modelo de random forest foi superior em todas as métricas, incluindo a mais importante, que era conseguir prever clientes que comprariam pelo site da empresa, com um recall de 0.92 e uma diferença de 42 verdadeiros positivos, em relação ao modelo de regressão logística.

Portanto, para essa variável, e essa base de dados, em questão, o modelo de random forest parece ser o mais indicado.